# Change these first
owner: FOX-X-BOT  # Your GitHub usernames
repo: Stark-Status # Your GitHub repository name

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

# Add your sites here
sites:
  - name: Cache Server
    url: https://www.cloudflare.com
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Permanent Drives
    url: https://www.mongodb.com
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Azure
    url: https://portal.azure.com/
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Virus Scan Bot
    url: $VIRUS_TOTAL
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Stark Mirror
    url: $JARVIS
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Stark Index
    url: https://starkmirror.stark-mirror.workers.dev
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: starkindustrystatus.vercel.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  favicon: https://github.com/StarkIndustriesTG/StarkIndustriesTG/main/Stark.png?raw=true
  # baseUrl: /Stark-Status
  theme: dark
  logoUrl: https://github.com/StarkIndustriesTG/StarkIndustriesTG/main/Stark.png?raw=true
  name: Stark Status
  introTitle: " "
  introMessage: " " 
  
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/StarkIndustriesTG
    - title: Telegram
      href: https://t.me/StarkAndIndustries

i18n:
  footer: "©️ 2022 [Stark](https://github.com/StarkIndustriesTG)"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

  up: "✅ Up"
  degraded: "⚠️ Degraded"
  down: "🚨 Down"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "✅ All systems operational"
  degradedPerformance: "⚠️ Degraded performance"
  completeOutage: "🚨 Complete outage"
  partialOutage: "🟧 Partial outage"  

commitMessages:
  commitAuthorName: "NKMBot"
  commitAuthorEmail: "uptime-bot@navaneethkm.gq"

workflowSchedule:
  uptime: "*/5 * * * *"
