# Change these first
owner: FOX-X-BOT  # Your GitHub username
repo: Stark-Status # Your GitHub repository name

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

# Add your sites here
sites:
  - name: Cache Server
    url: https://www.cloudflare.com
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Permanent Drives
    url: https://www.mongodb.com
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif
  - name: Azure
    url: Azure
    icon: https://raw.githubusercontent.com/navaneethkm004/my-images/main/giphy%20(1).gif

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: starkindustrystatus.vercel.app
  # Uncomment the following line if you don't have a custom domain and add your repo name
  favicon: https://github.com/navaneethkm004/my-images/blob/main/circle-cropped%20(7).png?raw=true
  # baseUrl: /Stark-Status
  theme: dark
  logoUrl: https://github.com/navaneethkm004/my-images/blob/main/circle-cropped%20(7).png?raw=true
  name: Stark Status
  introTitle: " "
  introMessage: " " 
  
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/StarkIndustriesTG
    - title: Telegram
      href: https://t.me/StarkAndIndustries

i18n:
  footer: "©️ 2022 [Stark](https://github.com/StarkIndustriesTG)"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

#  up: "✅ Up"
#  degraded: "⚠️ Degraded"
#  down: "🚨 Down"
#  liveStatusHtmlComment: "<!--live status-->"
#  allSystemsOperational: "✅ All systems operational"
#  degradedPerformance: "⚠️ Degraded performance"
#  completeOutage: "🚨 Complete outage"
#  partialOutage: "🟧 Partial outage"  

commitMessages:
  commitAuthorName: "NKMBot"
  commitAuthorEmail: "uptime-bot@navaneethkm.gq"

workflowSchedule:
  uptime: "*/15 * * * *"
